name: builds
on: [push]
jobs:
  ph2ed_proto:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - run: ./ci.bat
      - uses: actions/upload-artifact@v2
        with:
          name: ph2ed_proto
          path: ph2ed_proto/ph2ed_proto.exe
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest"
          files: ph2ed_proto.zip
